"""newtest drift

Revision ID: 0fc2c5693fd8
Revises: e1d2b8935898
Create Date: 2019-03-31 16:00:02.833085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc2c5693fd8'
down_revision = 'e1d2b8935898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift', sa.Column('requester_nickname', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drift', 'requester_nickname')
    # ### end Alembic commands ###
