"""add pending

Revision ID: 85516318c7f8
Revises: ab3a4d7d035d
Create Date: 2019-03-25 16:20:08.343589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85516318c7f8'
down_revision = 'ab3a4d7d035d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift', sa.Column('pending', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drift', 'pending')
    # ### end Alembic commands ###
