"""gift add create_time

Revision ID: adeda0a82566
Revises: 
Create Date: 2019-02-22 16:09:43.885418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'adeda0a82566'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('gift', sa.Column('create_time', sa.String(length=200), nullable=False))
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.drop_column('gift', 'create_time')
    op.drop_column('book', 'status')
    # ### end Alembic commands ###
