"""change drift phone_number

Revision ID: e1d2b8935898
Revises: 85516318c7f8
Create Date: 2019-03-27 16:21:23.400799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1d2b8935898'
down_revision = '85516318c7f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift', sa.Column('mobile', sa.String(length=20), nullable=False))
    op.drop_column('drift', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift', sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('drift', 'mobile')
    # ### end Alembic commands ###
